import SwiftUI
import SwiftData

@main
struct DodoClipApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    var sharedModelContainer: ModelContainer = {
        let schema = Schema([
            ClipItem.self,
            Collection.self,
            AppSettings.self
        ])

        let modelConfiguration = ModelConfiguration(
            schema: schema,
            isStoredInMemoryOnly: false
        )

        do {
            return try ModelContainer(
                for: schema,
                configurations: [modelConfiguration]
            )
        } catch {
            fatalError("Could not create ModelContainer: \(error)")
        }
    }()

    var body: some Scene {
        // Settings window (opened via menu)
        Settings {
            SettingsView()
        }
        .modelContainer(sharedModelContainer)
    }
}

/// Placeholder settings view
struct SettingsView: View {
    var body: some View {
        TabView {
            GeneralSettingsTab()
                .tabItem {
                    Label("General", systemImage: "gear")
                }

            ShortcutsSettingsTab()
                .tabItem {
                    Label("Shortcuts", systemImage: "keyboard")
                }

            RulesSettingsTab()
                .tabItem {
                    Label("Rules", systemImage: "checklist")
                }

            AboutSettingsTab()
                .tabItem {
                    Label("About", systemImage: "info.circle")
                }
        }
        .frame(width: 500, height: 350)
    }
}

struct GeneralSettingsTab: View {
    @ObservedObject private var settingsService = SettingsService.shared

    var body: some View {
        Form {
            Section {
                Toggle("Launch at login", isOn: Binding(
                    get: { settingsService.launchAtLogin },
                    set: { settingsService.launchAtLogin = $0 }
                ))
                Toggle("Show in menu bar", isOn: .constant(true))
            }

            Section("History") {
                Picker("Keep history for", selection: Binding(
                    get: { settingsService.historyLimit },
                    set: { settingsService.historyLimit = $0 }
                )) {
                    Text("100 items").tag(100)
                    Text("500 items").tag(500)
                    Text("1000 items").tag(1000)
                    Text("5000 items").tag(5000)
                }
            }
        }
        .formStyle(.grouped)
        .padding()
    }
}

struct ShortcutsSettingsTab: View {
    var body: some View {
        Form {
            Section("Global Shortcuts") {
                HStack {
                    Text("Show Panel")
                    Spacer()
                    Text("⇧⌘V")
                        .font(.system(.body, design: .monospaced))
                        .foregroundColor(.secondary)
                }

                HStack {
                    Text("Activate Paste Stack")
                    Spacer()
                    Text("⇧⌘C")
                        .font(.system(.body, design: .monospaced))
                        .foregroundColor(.secondary)
                }
            }
        }
        .formStyle(.grouped)
        .padding()
    }
}

struct RulesSettingsTab: View {
    @ObservedObject private var settingsService = SettingsService.shared

    var body: some View {
        Form {
            Section("Privacy") {
                Toggle("Ignore password managers", isOn: Binding(
                    get: { settingsService.ignorePasswordManagers },
                    set: { settingsService.ignorePasswordManagers = $0 }
                ))
                Toggle("Ignore auto-generated content", isOn: Binding(
                    get: { settingsService.ignoreAutoGenerated },
                    set: { settingsService.ignoreAutoGenerated = $0 }
                ))
            }

            Section("Ignored Apps") {
                if settingsService.ignoredAppBundleIDs.isEmpty {
                    Text("No apps ignored")
                        .foregroundColor(.secondary)
                } else {
                    ForEach(settingsService.ignoredAppBundleIDs, id: \.self) { bundleID in
                        IgnoredAppRow(bundleID: bundleID) {
                            settingsService.removeIgnoredApp(bundleID)
                        }
                    }
                }

                Button("Add App...") {
                    showAppPicker()
                }
            }
        }
        .formStyle(.grouped)
        .padding()
    }

    private func showAppPicker() {
        let panel = NSOpenPanel()
        panel.canChooseFiles = true
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = false
        panel.allowedContentTypes = [.application]
        panel.directoryURL = URL(fileURLWithPath: "/Applications")
        panel.message = "Select an application to ignore"
        panel.prompt = "Add"

        if panel.runModal() == .OK, let url = panel.url {
            if let bundle = Bundle(url: url), let bundleID = bundle.bundleIdentifier {
                settingsService.addIgnoredApp(bundleID)
            }
        }
    }
}

struct IgnoredAppRow: View {
    let bundleID: String
    let onRemove: () -> Void

    private var appName: String {
        if let appURL = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) {
            return appURL.deletingPathExtension().lastPathComponent
        }
        return bundleID
    }

    private var appIcon: NSImage? {
        if let appURL = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) {
            return NSWorkspace.shared.icon(forFile: appURL.path)
        }
        return nil
    }

    var body: some View {
        HStack(spacing: 8) {
            if let icon = appIcon {
                Image(nsImage: icon)
                    .resizable()
                    .frame(width: 20, height: 20)
            }

            VStack(alignment: .leading, spacing: 2) {
                Text(appName)
                    .font(.body)
                Text(bundleID)
                    .font(.caption)
                    .foregroundColor(.secondary)
            }

            Spacer()

            Button {
                onRemove()
            } label: {
                Image(systemName: "minus.circle.fill")
                    .foregroundColor(.red)
            }
            .buttonStyle(.plain)
        }
    }
}

struct AboutSettingsTab: View {
    private let appVersion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "1.0.0"

    var body: some View {
        VStack(spacing: 20) {
            Spacer()

            // App icon
            if let appIcon = NSApp.applicationIconImage {
                Image(nsImage: appIcon)
                    .resizable()
                    .frame(width: 80, height: 80)
                    .clipShape(RoundedRectangle(cornerRadius: 16))
            } else {
                Image(systemName: "clipboard")
                    .font(.system(size: 64))
                    .foregroundColor(.accentColor)
            }

            // App name and version
            VStack(spacing: 4) {
                Text("DodoClip")
                    .font(.system(size: 24, weight: .bold))

                Text("Version \(appVersion)")
                    .font(.system(size: 12))
                    .foregroundColor(.secondary)
            }

            // Description
            Text("A free, open-source clipboard manager for macOS")
                .font(.system(size: 13))
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)

            Spacer()

            // Links
            HStack(spacing: 16) {
                Link(destination: URL(string: "https://github.com/bluewave-labs/dodoclip")!) {
                    Label("GitHub", systemImage: "link")
                }

                Link(destination: URL(string: "https://github.com/bluewave-labs/dodoclip/issues")!) {
                    Label("Report issue", systemImage: "exclamationmark.bubble")
                }
            }
            .font(.system(size: 12))

            // Copyright
            Text("© Dr. Gorkem Cetin")
                .font(.system(size: 11))
                .foregroundColor(.secondary.opacity(0.7))

            Spacer()
        }
        .padding()
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

// MARK: - Previews

#Preview("Settings") {
    SettingsView()
}
